---
title: "Sentiment analysis on folkeviser comparison"
author: "Anna Aagaard Præst"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(tidytext) 
library(ggplot2) 
library(extrafont) 
library(dplyr) 
library(stringr) 
library(knitr)
library(kableExtra)
library(Sentida)


```

## SENTIDA analysis 

```{r installing packages and custom themes, eval=TRUE, include=FALSE, echo=FALSE}

#themes
custom_theme1 <- theme_minimal() +
  theme(
    panel.grid.major.y = element_line(linewidth = 2)
  )

custom_theme2 <- theme_minimal() +
  theme(
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10)
  )

custom_theme3 <- theme(
  text = element_text(family = "AU Passata", size = 12),
  axis.text.x = element_text(angle = 45, hjust = 1)
)

```

## Trylleviser
```{r loading data trylleviser, echo=TRUE, include=TRUE, eval=TRUE}
#loading data from cvs.file
trylleviser <- read.csv("/Users/annapraest/Desktop/DM_førsteprojekt/DM_07_eksamen_tidy/data/trylleviser_eksamen.csv", header = TRUE, stringsAsFactors = FALSE)
trylleviser <- separate(trylleviser, "songtitle.lyrics", into = c("songtitle", "lyrics"), sep = ";")
```

```{r tidying data for analysis trylleviser, echo=TRUE, eval=TRUE, include=TRUE}
#replacing various line break representations with a single space, replacing multiple spaces with a single space 
trylleviser <- trylleviser %>%
  mutate(lyrics_clean = trylleviser$lyrics %>%
           str_replace_all("\n", " ") %>%
           str_replace_all("\\s{2,}", " ")
  )
```

```{r showing dataframe trylleviser, echo=FALSE, eval=TRUE, include=TRUE}
trylleviser$lyrics_shortened <- paste(substr(trylleviser$lyrics, 1, 250), "...")
trylleviser$lyrics_clean_shortened <- paste(substr(trylleviser$lyrics_clean, 1, 250), "...")

knitr::kable(trylleviser[, c("songtitle", "lyrics_shortened", "lyrics_clean_shortened")], format = "html", escape = FALSE) %>%
  kable_styling(full_width = FALSE)

```

```{r sentiment analysis trylleviser, echo=TRUE, eval=TRUE, include=TRUE}
#calculating sentiment score for all trylleviser using lapply
sentiment_scores_trylleviser <- lapply(trylleviser$lyrics_clean, function(x) sentida(x, output = "total"))

#extracting numeric sentiment scores from the new output
numeric_scores <- sapply(sentiment_scores_trylleviser, function(x) as.numeric(unlist(x)))

#adding sentiment scores as a new column to the original dataframe
trylleviser$sentiment_scores <- numeric_scores
```

```{r sentiment analysis result trylleviser, echo=FALSE, eval=TRUE, include=TRUE}
trylleviser <- trylleviser %>% arrange(songtitle)

knitr::kable(trylleviser[, c("songtitle", "sentiment_scores")], format = "html") %>%
  kable_styling(full_width = FALSE)
```

```{r visualization sentiment analysis trylleviser, echo=TRUE, eval=TRUE, include=TRUE, fig.height=7}
ggplot(trylleviser, aes(x = songtitle, y = sentiment_scores)) +
  geom_bar(stat = "identity", fill = "darkred") +
  labs(title = "Trylleviser", x = "Folkeviser", y = "Sentiment score") +
  custom_theme1 + custom_theme2 + custom_theme3 +
  scale_y_continuous(limits = c(-50, 150 ), breaks = seq(-50, 150, by = 10))
```

## Trylleviser with words tokenized

```{r loading data trylleviser_token, echo=TRUE, include=TRUE, eval=TRUE}
#loading the data
trylleviser_token <- read.csv("/Users/annapraest/Desktop/DM_førsteprojekt/DM_07_eksamen_tidy/data/trylleviser_eksamen.csv", header = TRUE, stringsAsFactors = FALSE)
trylleviser_token <- separate(trylleviser_token, "songtitle.lyrics", into = c("songtitle", "lyrics"), sep = ";")
```

```{r tidying data for analysis trylleviser_token, echo=TRUE, eval=TRUE, include=TRUE}
#Replacing various line break representations with a single space, replacing multiple spaces with a single space, seperating songs into tokens (words) using unnest_tokens function
trylleviser_token <- trylleviser_token %>%
  mutate(lyrics_clean = trylleviser_token$lyrics %>%
           str_replace_all("\n", " ") %>%
           str_replace_all("\\s{2,}", " ")
  ) %>%
  unnest_tokens(word, lyrics_clean)
```

```{r showing trylleviser_token example, echo=FALSE, eval=TRUE, include=TRUE}
trylleviser_token$lyrics_shortened <- paste(substr(trylleviser_token$lyrics, 1, 250), "...")

#using a combination of head function and kable function
knitr::kable(head(trylleviser_token[, c("songtitle", "lyrics_shortened", "word")]), format = "html") %>%
  kable_styling(full_width = FALSE)
```

```{r sentiment analysis trylleviser_token, echo=TRUE, eval=TRUE, include=TRUE}
#sentiment score trylleviser_token

sentiment_scores_trylleviser_token <- lapply(trylleviser_token$word, function(x) sentida(x, output = "total"))

#extracting numeric sentiment scores from the new output
token_numeric_scores <- sapply(sentiment_scores_trylleviser_token, function(x) as.numeric(unlist(x)))

#adding sentiment scores as a new column to the original dataframe
trylleviser_token$sentiment_scores <- token_numeric_scores

```

```{r combing results by songtitle sentiment analysis trylleviser_token, echo=TRUE, eval=TRUE, include=TRUE}
#create new dataframe with the results grouped by songtitle
trylleviser_token_grouped <- trylleviser_token %>%
  group_by(songtitle) %>%
  summarize(sentiment_scores = sum(sentiment_scores))
```

```{r sentiment analysis result with tokenized words trylleviser, echo=FALSE, eval=TRUE, include=TRUE}
knitr::kable(trylleviser_token_grouped[, c("songtitle", "sentiment_scores")], format = "html") %>%
  kable_styling(full_width = FALSE)
```

```{r visualization sentiment analysis trylleviser_token, echo=TRUE, eval=TRUE, include=TRUE, fig.height=7}
ggplot(trylleviser_token_grouped, aes(x = songtitle, y = sentiment_scores)) +
  geom_bar(stat = "identity", fill = "darkred") +
  labs(title = "Trylleviser tokenized", x = "Folkeviser", y = "Sentiment score") +
  custom_theme1 + custom_theme2 + custom_theme3 +
  scale_y_continuous(limits = c(-50, 150), breaks = seq(-50, 150, by = 10))

```

```{r count of words included when tokenized, echo=TRUE, eval=TRUE, include=TRUE}
#counts how many words = 0.000000 (not included in sentiment analysis)
trylleviser_token_number_of_words <- trylleviser_token %>%
  group_by(songtitle) %>%
  summarise(words_with_score_0 = sum(sentiment_scores == 0.0000000),
            words_not_score_0 = sum(sentiment_scores != 0.0000000))

#count total number of words and add it to dataframe
trylleviser_token_number_of_words$combined_word_count <- trylleviser_token_number_of_words$words_with_score_0 + trylleviser_token_number_of_words$words_not_score_0

```

```{r showing words included when tokenized, echo=FALSE, eval=TRUE, include=TRUE}
#using kable function to show the count
knitr::kable(trylleviser_token_number_of_words)
```

## Trylleviser with words tokenized without stopwords

```{r loading data stopwords , echo=TRUE, eval=TRUE, include=TRUE}

#removing stopwords using Max Odsbjergs list of 19th century danish stopwords

#load data
stopwords_19thcentury <- read.csv("/Users/annapraest/Desktop/DM_førsteprojekt/DM_07_eksamen_tidy/data/19th_century_stopwords_DA_light.csv")

```

```{r removing stopwords from tokenized wordlist , echo=TRUE, eval=TRUE, include=TRUE}
#extract word column from stopwords_19thcentury as a vector string
stopwords_19thcentury_list <- stopwords_19thcentury$word

#filtering out the stopwords from column word in trylleviser_token using %in% 
trylleviser_token_no_stopwords <- trylleviser_token[!trylleviser_token$word %in% stopwords_19thcentury_list, ]

#counts how many words = 0.000000 (not included in sentiment analysis) when not including stopwords
trylleviser_token_number_of_words_no_stopwords <- trylleviser_token_no_stopwords %>%
  group_by(songtitle) %>%
  summarise(words_with_score_0 = sum(sentiment_scores == 0.0000000),
            words_not_score_0 = sum(sentiment_scores != 0.0000000))


#count total number of words and add it to dataframe
trylleviser_token_number_of_words_no_stopwords$combined_word_count <- trylleviser_token_number_of_words_no_stopwords$words_with_score_0 + trylleviser_token_number_of_words$words_not_score_0

```

```{r showing words included when tokenized without stopwords, echo=FALSE, eval=TRUE, include=TRUE}
#using kable function to show the count
knitr::kable(trylleviser_token_number_of_words_no_stopwords)
```

## Combining results on sentiment analysis

```{r combining dataframes into one trylleviser_combined, echo=TRUE, eval=TRUE, include=FALSE}
#merging existing dataframes and sorting them by common identifier songtitle
trylleviser_combined <- merge(trylleviser_token_grouped, trylleviser, by = "songtitle")
```

```{r visualization comparison sentiment analysis trylleviser, echo=TRUE, eval=TRUE, include=TRUE, fig.height=8, fig.width=8}

ggplot(trylleviser_combined, aes(x = songtitle)) +
  geom_point(aes(y = sentiment_scores.x, color = "trylleviser"), size = 2.5) +
  geom_point(aes(y = sentiment_scores.y, color = "trylleviser_tokenized"), size = 2.5) +
  scale_color_manual(values = c("trylleviser" = "darkblue", "trylleviser_tokenized" = "darkred"),
                     name = "",
                     labels = c("trylleviser", "trylleviser tokenized")) +
  labs(title = "Sentiment scores comparison for trylleviser",
       x = "Trylleviser", y = "Sentiment score") +
  custom_theme1 + custom_theme2 + custom_theme3 +
  scale_y_continuous(limits = c(-50, 150), breaks = seq(-50, 150, by = 10))
```